import { chromium } from 'playwright';
import path from 'node:path';
import { startServer } from './server.mjs';
const root = '/home/user/flight-landing-game';
const out = '/tmp/claude-0/-home-user-flight-landing-game/3b3f02f8-63cc-557a-b5f7-892b15b88c28/scratchpad';
const { server, url } = await startServer(root);
const browser = await chromium.launch({ headless: true, args: ['--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader', '--ignore-gpu-blocklist'] });
const page = await browser.newPage({ viewport: { width: 1024, height: 576 } });
page.on('pageerror', (e) => console.log('PAGE ERROR', e.message));
await page.goto(url + '/', { waitUntil: 'load' });
await page.waitForFunction(() => window.__sim, null, { timeout: 60000 });
const frames = (n) => page.evaluate((n) => new Promise((res) => { const f0 = window.__sim.stats.frames; const chk = () => (window.__sim.stats.frames - f0 >= n ? res() : requestAnimationFrame(chk)); chk(); }), n);
const shot = async (name) => { await frames(2); await page.screenshot({ path: path.join(out, name + '.png') }); console.log('shot', name); };
await page.evaluate(() => window.__sim.start({ scenarioId: 'clear', startId: 'short', mode: 'game', sound: false, night: false, seed: 11 }));
await frames(3);
await shot('ck-start');
await page.evaluate(() => { window.__sim.inputManager.look.down = true; }); await shot('ck-pedestal'); await page.evaluate(() => { window.__sim.inputManager.look.down = false; });
await page.evaluate(() => window.__sim.autopilot());
await page.evaluate(() => window.__sim.setTimeScale(8));
await page.waitForFunction(() => window.__sim.state().agl < 60, null, { timeout: 300000 });
await page.evaluate(() => window.__sim.setTimeScale(1));
await shot('ck-200ft');
await page.evaluate(() => window.__sim.setTimeScale(4));
await page.waitForFunction(() => window.__sim.state().agl < 4, null, { timeout: 300000 });
await page.evaluate(() => window.__sim.setTimeScale(1));
await shot('ck-flare');
console.log('state', JSON.stringify(await page.evaluate(() => { const s = window.__sim.state(); return { pitch: s.pitch * 57.3, agl: s.agl, ias: s.ias }; })));
await browser.close(); server.close();
