import assert from 'node:assert/strict';
import {qualifiesForHigh} from '../js/graphics-quality.js';
assert.equal(qualifiesForHigh(Array(48).fill(16.7)),true);
assert.equal(qualifiesForHigh(Array(48).fill(33.3)),false);
assert.equal(qualifiesForHigh([...Array(40).fill(16.7),...Array(8).fill(50)]),false,'Reject unstable frame pacing');
assert.equal(qualifiesForHigh(Array(12).fill(16.7)),false,'Incomplete measurement stays conservative');
assert.equal(qualifiesForHigh([...Array(47).fill(16.7),NaN]),false);
globalThis.location={search:''};globalThis.window={matchMedia:()=>({matches:false})};
const {ResolutionScaler}=await import('../js/platform.js');
const world=()=>({autoQuality:true,quality:'high',ratio:1,setPixelRatio(r){this.ratio=r;},reduceQuality(){this.quality='low';}});
const w=world(),scaler=new ResolutionScaler(w,{enabled:true,start:1});
for(let i=0;i<500;i++)scaler.frame(33.3,true);
assert.equal(w.quality,'low','Sustained slow flight reduces effects after resolution reaches its floor');
assert.equal(w.ratio,.7);
const stalled=world(),s=new ResolutionScaler(stalled,{enabled:true,start:1});
s.frame(400,true);s.frame(16.7,true);assert.equal(stalled.quality,'high','An isolated hitch does not change the tier');
for(let i=0;i<8;i++)s.frame(400,true);
assert.equal(stalled.quality,'low','Repeated long frames must not escape the performance guard');
const explicit=world();explicit.autoQuality=false;const fixed=new ResolutionScaler(explicit,{enabled:false,start:1});
for(let i=0;i<500;i++)fixed.frame(33.3,true);
assert.equal(explicit.quality,'high');assert.equal(explicit.ratio,1,'Explicit quality/DRS overrides are respected');
console.log('Automatic graphics: measured fast, slow, unstable and incomplete frames passed');
