// Deliver the original Blender farm with bounded geometry/texture transfer.
import {NodeIO} from '@gltf-transform/core';
import {ALL_EXTENSIONS} from '@gltf-transform/extensions';
import {prune,dedup,weld,meshopt,textureCompress} from '@gltf-transform/functions';
import {MeshoptEncoder} from 'meshoptimizer';
import sharp from 'sharp';
import fs from 'node:fs/promises';
await MeshoptEncoder.ready;
const io=new NodeIO().registerExtensions(ALL_EXTENSIONS).registerDependencies({'meshopt.encoder':MeshoptEncoder});
const source='test/output/farm-sources';
const doc=await io.read(`${source}/farm-source.glb`);
await doc.transform(prune(),dedup(),weld(),textureCompress({encoder:sharp,targetFormat:'webp',quality:86,resize:[1024,1024]}));
await doc.transform(meshopt({encoder:MeshoptEncoder,level:'high',quantizePosition:16}));
await io.write('assets/scenery/valley-farm.glb',doc);
await doc.transform(textureCompress({encoder:sharp,targetFormat:'webp',quality:82,resize:[512,512]}));
await io.write('assets/scenery/valley-farm-low.glb',doc);
for(const channel of ['color','normal','rough'])for(const low of [false,true])
 await sharp(`${source}/gravel_floor/${channel}.jpg`).resize(low||channel!=='color'?512:1024).webp({quality:channel==='normal'?90:85}).toFile(`assets/scenery/farm-gravel-${channel}${low?'-low':''}.webp`);
const sources=[];
for(const name of ['weathered_brown_planks','gravel_floor']){
 const info=JSON.parse(await fs.readFile(`${source}/${name}/info.json`));
 const files=JSON.parse(await fs.readFile(`${source}/${name}/files.json`));
 sources.push({name,url:`https://polyhaven.com/a/${name}`,license:'CC0-1.0',authors:info.authors,
 maps:Object.fromEntries(['Diffuse','nor_gl','Rough'].map(k=>[k,files[k]['1k'].jpg]))});
}
const placements=JSON.parse(await fs.readFile(`${source}/placement.json`));
const assetFiles=['valley-site.json','valley-farm.glb','valley-farm-low.glb',...['color','normal','rough'].flatMap(c=>[`farm-gravel-${c}.webp`,`farm-gravel-${c}-low.webp`])];
const bytes=Object.fromEntries(await Promise.all(assetFiles.map(async f=>[f,(await fs.stat('assets/scenery/'+f)).size])));
await fs.writeFile('assets/scenery/farm-sources.json',JSON.stringify({geometryLicense:'MIT',geometry:'Original valley farm and six neighboring roadside buildings, generated by tools/prepare-farm.py in Blender. Footprints retained from approach data; source heights are estimates and complete-building heights, architecture and grounds are interpreted, not a surveyed reconstruction.',placements,sources,bytes},null,2)+'\n');
console.log(bytes);
