"""Bundle USGS 3DEP heights registered to the existing NAIP imagery (Pillow).

python3 tools/prepare-elevation.py [--cache /path/to/cache]
No network, asynchronous height change, or account is needed while playing.
"""
import argparse
import base64
import hashlib
import json
import math
from pathlib import Path
import struct
import subprocess
from urllib.parse import urlencode
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
parser = argparse.ArgumentParser()
parser.add_argument('--cache', type=Path, default=ROOT / 'test/output/elevation-source')
args = parser.parse_args()
args.cache.mkdir(parents=True, exist_ok=True)
lat, lon = 40.828, -77.615
r = 6378137
cx = r * math.radians(lon)
cy = r * math.log(math.tan(math.pi / 4 + math.radians(lat) / 2))
scale = 1 / math.cos(math.radians(lat))
service = 'https://elevation.nationalmap.gov/arcgis/rest/services/3DEPElevation/ImageServer'
records, modules = [], []
for name, span, east, count in [('region', 80000, 16000, 513), ('approach', 24000, 5000, 513)]:
    step = span / (count - 1)
    # ArcGIS samples pixel centres. Extend the bounds by half a cell so our first
    # and last samples land exactly on the requested world-space endpoints.
    bbox = [cx+(east-span/2-step/2)*scale, cy-(span/2+step/2)*scale,
            cx+(east+span/2+step/2)*scale, cy+(span/2+step/2)*scale]
    query = dict(bbox=','.join(map(str, bbox)), bboxSR=3857, imageSR=3857,
                 size=f'{count},{count}', format='tiff', pixelType='F32',
                 interpolation='RSP_BilinearInterpolation',
                 renderingRule=json.dumps({'rasterFunction': 'None'}), f='image')
    url = service + '/exportImage?' + urlencode(query)
    source = args.cache / f'{name}.tif'
    if not source.exists():
        subprocess.run(['curl', '-fLsS', '--retry', '2', '--max-time', '120', url, '-o', str(source)], check=True)
    im = Image.open(source)
    assert im.mode == 'F' and im.size == (count, count), 'Expected raw single-band metre elevations'
    values = list(im.getdata())
    assert all(math.isfinite(v) and 0 <= v < 8000 for v in values), 'Missing or invalid DEM samples'
    packed = struct.pack('<' + 'H'*len(values), *(round(v*4) for v in values))
    encoded = base64.b64encode(packed).decode('ascii')
    metadata = dict(name=name, count=count, x=east-span/2, z=-span/2, step=step, quantum=.25)
    modules.append('export const ' + name.upper() + ' = ' + json.dumps(metadata)[:-1] + ', data:\n' +
                   '\n+ '.join(json.dumps(encoded[i:i+120]) for i in range(0, len(encoded), 120)) + '};\n')
    records.append(dict(**metadata, source=url, sha256=hashlib.sha256(source.read_bytes()).hexdigest(),
                        elevationRange=list(im.getextrema()), license='Public domain — USGS 3DEP'))
    print(name, im.getextrema(), len(packed), 'bytes')
out = ROOT / 'assets/scenery'
(out / 'elevation.js').write_text('// Generated by tools/prepare-elevation.py. Public-domain USGS 3DEP.\n' + ''.join(modules))
(out / 'elevation-sources.json').write_text(json.dumps(dict(
    service=service, registration=dict(latitude=lat, longitude=lon, projection='EPSG:3857', scale=scale),
    notes='North-up pixel centres. Quantized to 0.25 m. Runtime subtracts a fictional 350 m datum and locally grades Westhaven airport; these are not navigation data.',
    sources=records), indent=2) + '\n')
